server:
  port: 8081 # Укажите уникальный порт для каждого сервиса

spring:
  application:
    name: account-service # Уникальное имя для сервиса
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Убедитесь, что схема базы данных будет обновляться автоматически
    show-sql: true # Логирование SQL-запросов для отладки

logging:
  level:
    org.springframework: INFO