server:
  port: 8888 # Укажите уникальный порт для каждого сервиса

spring:
  application:
    name: config-service # Уникальное имя для сервиса
  datasource:
    url: jdbc:postgresql://localhost:5432/config_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Убедитесь, что схема базы данных будет обновляться автоматически
    show-sql: true # Логирование SQL-запросов для отладки

logging:
  level:
    org.springframework: INFO